/**
 * App copy, limits, and static options. No hardcoded data in components.
 */
export const appConfig = {
  steps: [
    { label: 'Idea', phase: 'idea' },
    { label: 'Features', phase: 'features' },
    { label: 'Personas', phase: 'persona-suggestion' },
    { label: 'Journeys', phase: 'personas' },
    { label: 'Review', phase: 'review' },
    { label: 'API Map', phase: 'diagram' },
    { label: 'Jira Plan', phase: 'jira' },
  ],
  minFeatures: 8,
  maxFeatures: 12,
  minPersonas: 2,
  maxPersonas: 4,
  stepsPerJourney: 5,
  journeysPerPersona: 2,
  ideaPlaceholder: 'e.g. A mobile-first e-commerce app with personalised shopping, one-click checkout and a loyalty rewards programme…',
  exampleIdeas: [
    'Mobile checkout experience',
    'B2B procurement portal',
    'Subscription box platform',
    'Healthcare patient portal',
  ],
  ideaScreen: {
    badge: 'Powered by your enterprise API catalog',
    title: "What are you building today?",
    titleEmphasis: "building today?",
    subtitle: "Describe your product idea or chat to refine it. When ready, summarise and then continue to features.",
    ideaPlaceholder: 'Optional: type an initial idea or context here…',
    chatPlaceholder: 'Type a message to refine your idea…',
    sendCta: 'Send',
    summariseCta: 'Summarise idea →',
    summarisingLabel: 'Summarising…',
    summaryTitle: 'Your idea summary',
    summarySubtitle: 'Review below. If something is missing, continue chatting and summarise again. When you\'re happy, continue to features.',
    continueChatCta: 'Continue chat',
    continueToFeaturesCta: 'Continue to features →',
    continueToFeaturesLoading: 'Breaking into features…',
    shortcutHint: '⌘ + Enter',
    errors: {
      chat: 'Could not send message',
      summarise: 'Could not summarise',
    },
  },
  featuresScreen: {
    stepLabel: 'STEP 1 — FEATURE SCOPING',
    title: 'Confirm your product features',
    subtitle: "We've inferred features from your idea. Toggle any on or off, or add and edit features, before we map user journeys — no API calls yet.",
    mapJourneysCta: 'Map User Journeys →',
    of: 'of',
    featuresSelected: 'features selected',
    regenerateCta: 'Regenerate features',
    addFeatureCta: 'Add feature',
    editFeatureCta: 'Edit',
    addFeatureTitle: 'New feature',
    editFeatureTitle: 'Edit feature',
    featureTitlePlaceholder: 'Feature title (e.g. One-click checkout)',
    featureDescPlaceholder: 'Short description of what this feature does',
    saveFeatureCta: 'Save',
    cancelCta: 'Cancel',
  },
  personaSuggestionScreen: {
    stepLabel: 'STEP 2 — PERSONA SUGGESTION',
    title: 'Suggested personas for your product',
    subtitle: 'Review and edit persona suggestions. Select which to include, then confirm to generate journey maps.',
    confirmCta: 'Confirm Personas →',
    addCustom: 'Add custom persona',
    primaryBadge: 'Primary',
    regenerateCta: 'Regenerate suggestions',
  },
  personasScreen: {
    stepLabel: 'STEP 2 — USER JOURNEY MAPPING',
    title: 'User journeys by persona',
    subtitle: "Deselect any persona you won't support at launch. All API matching happens only after you confirm.",
    reviewCta: 'Review & Confirm →',
    stepsLabel: 'steps',
    back: '← Back',
    personasLabel: 'personas',
    regenerateCta: 'Regenerate journeys',
  },
  reviewScreen: {
    stepLabel: 'STEP 3 — FINAL REVIEW',
    title: 'Ready to scan your API catalog',
    subtitle: "Confirm everything looks right — then we'll make the first and only call to your backend API registry.",
    scanCta: 'Run API Coverage Scan',
    warningTitle: 'First API call to your backend.',
    warningBody: 'Clicking scan will query your enterprise API registry. All previous steps used zero network calls.',
    back: '← Back',
    featuresLabel: 'Features',
    personasLabel: 'Personas',
    stepsToAnalyse: 'Steps to Analyse',
  },
  scanningScreen: {
    subtext: 'Querying enterprise API registry…',
  },
  diagramScreen: {
    coverageTitle: 'of your workflow is already in your API catalog',
    coverageSub: 'steps covered',
    apisNeedBuild: 'API(s) need to be built',
    viewJiraCta: 'View Jira Plan →',
    legendExact: 'API Available',
    legendPartial: 'Enhance',
    legendNone: 'Needs Build',
    clickContract: 'Click any node to view contract →',
    apisMatched: 'APIs matched',
    needsBuildBannerTitle: 'API(s) need to be built — estimated',
    needsBuildBannerSub: 'man-days total',
    needsBuildBannerBody: 'Auto-generated Jira stories with effort estimates are ready.',
    rescanCta: 'Re-scan',
  },
  jiraScreen: {
    stepLabel: 'DEVELOPMENT PLAN',
    title: 'Jira Stories for Missing APIs',
    subtitle: 'Auto-generated tickets with effort estimates. Push directly to your Jira project.',
    backToDiagram: '← API Diagram',
    missingApis: 'Missing APIs',
    manDays: 'Man-Days',
    storyPoints: 'Story Points',
    sprintsEst: 'Sprints Est.',
    userStory: 'USER STORY',
    acceptanceCriteria: 'ACCEPTANCE CRITERIA',
    dependencies: 'DEPENDENCIES',
    copyStory: 'Copy Story',
    createInJira: 'Create in Jira',
    exportCsv: 'Export CSV',
    copyAll: 'Copy All',
    pushToJira: 'Push to Jira',
    totalEstimate: 'Total estimate:',
    manDaysAcross: 'man-days across',
    sprints: 'sprints',
    totalEstimateSub: 'Assuming 2-week sprints with a squad of 3–4 engineers',
    generationFailed: 'Generation failed — retry',
    rescanCta: 'Re-scan',
  },
  header: {
    appName: 'IdeaGPT',
    badge: 'ENTERPRISE',
    startOver: '← Start Over',
    coverageLabel: 'API Coverage',
  },
  errors: {
    chat: 'Could not send message',
    summarise: 'Could not summarise',
    features: 'Could not analyse idea',
    personaSuggestions: 'Could not suggest personas',
    journeys: 'Could not generate journeys',
    scan: 'Scan failed',
    jira: 'Jira generation failed',
    retry: 'Retry',
  },
};
